config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web => '/sidekiq'

  root 'reports#index'

  get 'sign_in' => 'sessions#new'
  delete 'sign_out' => 'sessions#destroy'

  resources :sessions, only: [:index, :create, :destroy]
  resources :verboice_callbacks, only: [:index]
  resources :dashboards, only: [:index]
  resources :calendars, only: [:index]
  resources :weeks, only: [:index]

  resources :places do
    collection do
      get 'ods_list'
      get 'download_template'
      post 'confirm_upload_location'
      post 'upload_location'
      get 'import'
      get 'export_as_csv'
    end
  end

  resources :users do
    collection do
      get 'profile'
      put 'change_profile'
      get 'download_template'
      post 'confirmed_upload_users'
      post 'upload_users'
      get 'by_place'
      get 'search'
      get 'import'
    end

    member do
      put 'reset'
    end
  end

  resources :settings, only: [:index]
  put 'update_settings' => 'settings#update_settings'

  put 'verboice' => 'settings#verboice'
  get 'project_variables' => 'settings#project_variables'
  get 'external' => 'settings#external'

  get '/steps/manifest' => 'steps#manifest', defaults: { format: :xml }
  post '/steps/validate_hc_worker' => 'steps#validate_hc_worker'

  resources :reports, only: [:index, :destroy] do
    member do
      put :toggle_status
      put :update_week
    end

    collection do
      get :export_as_csv
      get :query_piechart
    end
  end

  resources :report_variables, only: [] do
    member do
      get :play_audio
    end
  end

  resources :variables

  resources :channels do
    member do
      put 'state'
    end
  end
  resources :alerts do
    collection do
      get 'log'
    end
  end
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                   :integer          not null, primary key
#  username             :string(255)
#  name                 :string(255)
#  password_digest      :string(255)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  email                :string(255)
#  phone                :string(255)
#  role                 :string(255)
#  place_id             :integer
#  phone_without_prefix :string(255)
#  phd_id_id            :integer
#  phd_id               :integer
#  od_id                :integer
#  channels_count       :integer
#
# Indexes
#
#  index_users_on_phd_id_id  (phd_id_id)
#  index_users_on_place_id   (place_id)
#

class User < ActiveRecord::Base
  has_secure_password(validations: false)
  audited

  belongs_to :place
  belongs_to :phd, class_name: 'Place', foreign_key: 'phd_id'
  belongs_to :od, class_name: 'Place', foreign_key: 'od_id'

  has_many :reports, dependent: :nullify
  has_many :channels
  has_many :alerts
  # password must be present within 6..72
  validates :place_id, presence: true, if: ->(u) { !u.is_admin? }

  validates :password, presence: true, on: :create
  validates :password, length: { in: 6..72}, on: :create
  validates :password, confirmation: true

  # email must be in a valid format and has unique value if it is being provided
  validates :email, email: true, if: ->(u) { u.email.present? }
  validates :email, uniqueness: true, if: ->(u) { u.email.present? }

  validates :phone, uniqueness: true, if: ->(u) { u.phone.present? }

  validates :phone, presence: {message: "Health Center user must has a phone number"}, if: ->(u) { u.place && u.place.is_kind_of_hc?}

  validates :name, presence: true

  validates :username, presence: true
  validates :username, uniqueness: true

  ROLE_ADMIN  = 'Admin'
  ROLE_NORMAL = 'Normal'

  before_save :normalize_attrs
  before_save :set_place_tree

  attr_accessor :old_password

  def self.search phone
    @users = where("1=1")
    @users = where(["phone LIKE ?", "%#{phone}%"]) unless phone.blank?
    @users
  end

  def self.by_place place_id
    users = User.order("name DESC").all
    if(place_id.present?)
      users = users.where(place_id: place_id)
    end
    users
  end

  def set_place_tree
    if self.place
      self.phd = self.place.phd
      self.od  = self.place.od
    end
  end

  def normalize_attrs
    self.role = User::ROLE_NORMAL unless self.role.present?
    self.username.downcase!
    self.phone_without_prefix = self.phone.present? ? Tel.new(self.phone).without_prefix : nil
  end

  def self.authenticate(username, password)
    user = User.find_by!(username: username.downcase)
    user.authenticate(password)
  rescue ActiveRecord::RecordNotFound
    false
  end

  def self.visible_roles
    [ROLE_NORMAL, ROLE_ADMIN]
  end

  def is_admin?
    role == User::ROLE_ADMIN
  end

  def is_normal?
    role == User::ROLE_NORMAL
  end

  def change_password old_password, new_password, confirm
    if self.authenticate(old_password)
      self.password = new_password
      self.password_confirmation = confirm
      save
    else
      errors.add(:old_password, 'does not matched')
      false
    end
  end

  def self.hc_worker? phone_number
    phone_without_prefix = Tel.new(phone_number).without_prefix
    user = User.find_by(phone_without_prefix: phone_without_prefix)
    !user.nil? && user.place && user.place.is_kind_of_hc?
  end

  def self.decode_and_validate_user_csv(string)
    csv = CSV.parse(string)
    errors = []
    datas = []
    index = 0
    csv.slice!(0)
    csv.each do |row|
      valid = validate_row(index, row, csv)
      unless valid[:status]
        row.push(valid[:errors])
      end
      datas.push row
      index = index + 1
    end
    return {:data => datas}
  end

  def self.validate_row(index, row, csv)
    if row[4].strip.present? and row[5].strip.present? and row[4] != row[5]
      errors.push({:type => 'not_match', :field => 'password'})
    elsif row[4].strip.empty? or row[5].strip.empty?
      errors.push({:type => 'missing', :field => 'password'})
    end
    if row[6].strip.present?
      place = Place.find_by_code(row[6])
      unless place
        errors.push({:type => 'unknown', :field => 'place'})
      else
        row[6] = "#{place.name}(#{place.code}) - #{place.kind_of}"
      end
    elsif row[4].strip.empty? or row[5].strip.empty?
      errors.push({:type => 'missing', :field => 'place'})
    end
    errors = calculateError(csv, row, index)

    list_errors = generateErrorText(errors)

    if list_errors.size > 0
      return {:status => false, errors: list_errors}
    else
      return {:status => true}
    end
  end

  def self.calculateError(csv, row, index)
    errors = []
    i = 0
    errors.push({:type => 'duplicate', :field => 'login', :index => nil}) if User.find_by_username(row[0])
    # errors.push({:type => 'duplicate', :field => 'email', :index => nil}) if User.find_by_email(row[2])
    errors.push({:type => 'duplicate', :field => 'phone', :index => nil}) if User.find_by_phone(row[3])
    csv.each do |value|
      if i < index.to_i
        if row[0] == value[0]
          errors.push({:type => 'duplicate', :field => 'login', :index => (i+1)})
        elsif row[0].strip.empty?
          errors.push({:type => 'missing', :field => 'login'})
        end
        # if row[2] == value[2]
        #   errors.push({:type => 'duplicate', :field => 'email', :index => (i+1)})
        # elsif row[2].strip.empty?
        #   errors.push({:type => 'missing', :field => 'email'})
        # end
        if row[3] == value[3]
          errors.push({:type => 'duplicate', :field => 'phone', :index => (i+1)})
        elsif row[3].strip.empty?
          errors.push({:type => 'missing', :field => 'phone'})
        end
      end
      i = i + 1
    end
    return errors;
  end

  def self.generateErrorText(errors)
    list_errors = []
    errors.each do |error|
      case error[:field]
      when 'login'
        if error[:type] == 'duplicate'
          list_errors.push(generateDuplicateErrrorText(error[:index], "login"))
        elsif error[:type] == 'missing'
          list_errors.push(generateMissingErrrorText("login"))
        end
      when 'email'
        if error[:type] == 'duplicate'
          list_errors.push(generateDuplicateErrrorText(error[:index], "email"))
        elsif error[:type] == 'dupmissinglicate'
          list_errors.push(generateMissingErrrorText("email"))
        end
      when 'phone'
        if error[:type] == 'duplicate'
          list_errors.push(generateDuplicateErrrorText(error[:index], "phone number"))
        elsif error[:type] == 'missing'
          list_errors.push(generateMissingErrrorText("phone number"))
        end
      when 'password'
        if error[:type] == 'not_match'
          list_errors.push("Password not match on row #{index}")
        elsif error[:type] == 'missing'
          list_errors.push("Password or confirmation password is missing")
        end
      when 'place'
        if error[:type] == 'missing'
          list_errors.push("Place is missing")
        elsif error[:type] == 'unknown'
          list_errors.push("Place is unknown")
        end
      end
    end
    return list_errors
  end

  def self.generateDuplicateErrrorText(index, field)
    if index
      return "Duplicated #{field} value on row #{index}."
    else
      return "Duplicated #{field} with existing user #{field}."
    end
  end

  def self.generateMissingErrrorText(field)
    return "Missing #{field} value."
  end

  def self.decode_and_save_user_csv(string)
    csv = CSV.parse(string)
    datas = []
    csv.slice!(0)
    csv.each do |row|
      datas.push row
      place = Place.find_by_code(row[6].strip)
      phd_id = place.phd.id
      od_id = nil
      od_id = place.od.id if place.od
      User.create!(
          username: row[0],
          name: row[1],
          email: row[2],
          phone: row[3],
          role: "Normal",
          place_id: place.id,
          password: row[4],
          password_confirmation: row[5],
          phd_id: phd_id,
          od_id: od_id
      )
    end
    return {:data => datas}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  authorize_resource :except => [:change_profile]

  def index
    @place_id = params[:place_id]
    @users = User.by_place(@place_id).page(params[:page])
    render :by_place, layout: false if request.xhr?

  end

  def search
    @users = User.search(params[:phone]).page(params[:page])
    @place_id = @users.first.place_id if @users.length == 1
    render :index
  end

  def by_place
    @users = User.by_place(params[:place_id]).page(params[:page])
    render layout: false
  end

  def new
    @place = Place.find(params[:place_id])
    @user = User.new(place: @place)
  end

  def create
    @user = User.new(filter_params)
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if(@user.save)
      redirect_to  users_with_ref_path(@user.place_id), notice: 'User has been created successfully'
    else
      flash.now[:alert] = 'Failed to save user'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(filter_params)
      redirect_to users_with_ref_path(@user.place_id), notice: 'User has been updated successfully'
    else
      flash.now[:alert] = 'Failed to update user'
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    place_id = @user.place_id

    if @user.destroy
      redirect_to users_with_ref_path(place_id), notice: 'User has been deleted'
    else
      redirect_to users_with_ref_path(place_id), alert: 'Failed to remove users'
    end
  end

  def reset
    @user = User.find(params[:id])
    @random_password =  RandomWord.child_word_from_file("#{Rails.root}/public/ref/words.txt")
    @user.password = @random_password

    if !@user.save
      redirect_to edit_user_path(@user), alert: "Failed to reset password for this user. Please try again"
    end
  end

  def change_profile
    @old_password = params[:user][:old_password]
    @password = params[:user][:password]
    @password_confirmation = params[:user][:password_confirmation]

    if current_user.change_password(@old_password, @password, @password_confirmation)
      flash.now.notice = 'Your password has been changed successfully'

      @old_password = ''
      @password = ''
      @password_confirmation = ''
    else
      flash.now.alert =  current_user.errors.full_messages.first
    end
    render :profile
  end

  def profile
  end

  def import
  end

  def download_template
    respond_to do |format|
      format.json  { render :json => result }
      format.csv {
        content = "login,full_name,email,phone_number,password,password_confirmation,location_code \n" + 
        "example,example user,example@sampledomain.org.kh,8551234432233,samplepassword,samplepassword,100 \n" +
        "example1,example user1,example1@sampledomain.org.kh,855123443332,samplepassword,samplepassword,100"
        render :text => content
      }
    end
  end

  def upload_users
    csv_string = File.read(params[:users].path, :encoding => 'utf-8')
    users = User.decode_and_validate_user_csv(csv_string)
    render :json => users, :root => false
  end

  def confirmed_upload_users
    csv_string = File.read(params[:users].path, :encoding => 'utf-8')
    users = User.decode_and_save_user_csv(csv_string)
    render :json => users, :root => false
  end

  private

  def users_with_ref_path(place_id)
    users_path(place_id: place_id)
  end

  def filter_params
    params.require(:user).permit(:username, :name, :email, :phone, :place_id  )
  end
end

app/views/users/_form.html.erb
<%=display_hierachy_for(@user.place) %>

<%=simple_form_for(@user, html: { class: 'form-inline form'}) do |f| %>
  <%#= errors_for @user %>

  <%=f.input :place_id, as: :hidden %>
  <%=f.input :username, label: 'Login', input_html: {class: 'form-control'} %>
  <%=f.input :phone, label: 'Phone Number', required: @user.place.is_kind_of_hc? ,input_html: {class: 'form-control'} %>
  <%=f.input :name, label: 'Full Name', input_html: {class: 'form-control'} %>
  <%=f.input :email, input_html: {class: 'form-control'} %>

  <% if @user.new_record? %>
    <%=f.input :password, input_html: {class: 'form-control'} %>
    <%=f.input :password_confirmation, required: true, label: 'Confirm', input_html: {class: 'form-control'} %>
  <% end %>

  <div class='form-group form-action-group'>
    <label class='control-label'></label>

    <% if !@user.new_record? && @user != current_user  %>
    <%= link_to "Reset password", reset_user_path(@user), 
                :method => :put, 
                :confirm => 'Are you sure to reset password for this user?' ,
                :class => 'btn btn-danger' %>
    <%end %>

    <%=f.submit 'Save', class: 'btn btn-primary' %>

  </div>

<% end %>

app/views/users/_list.html.erb
<% if users.length > 0 %>
  <table class='table table-striped table-bordered table'>
    <thead>
      <tr>
        <td>Login</td>
        <td>Full Name</td>
        <td>Email</td>
        <td>Number</td>
        <td>Role</td>
        <td class='td-last'></td>
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
        <tr>
          <td><%= link_to user.username, edit_user_path(user) %></td>
          <td><%=user.name %></td>
          <td><%=user.email%></td>
          <td><%= highlight(user.phone, params[:phone]) %></td>
          <td><%=user.role%></td>
          <td class='td-last'>
            <% if !user.is_admin? %>
             <%= link_edit " ", edit_user_path(user)  %>
             <%= link_destroy " ", user_path(user), method: :delete, data: { confirm: 'Are you sure to delete' } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p style='margin: 30px 0px;'> There is no user for this place </p>
<% end %>

<%= link_to 'New User', new_user_path(place_id: params[:place_id]), class: 'new-user btn btn-primary btn-app' if params[:place_id].present? %>

<div class='tree-content-paginate' >
  <%= paginate_for(@users)%>
</div>

app/views/users/by_place.html.erb
<%= render 'users/list', users: @users %>

app/views/users/edit.html.erb
<% content_for(:title) { "User Modification"} %>
<%= breadcrumb [ {"Health Structure" => users_path(place_id: @user.place_id)}, {"User Modification" => nil}] %>

<%= page_header "User Modification" %>

<%= render 'form' %>

app/views/users/import.html.erb
<%= breadcrumb [ {"Health Structure" => places_path()}, {"Import user" => nil}] %>
<div class="fuelux-wizard-container">
  <!-- #section:plugins/fuelux.wizard.steps -->
  <ul class="steps">
    <li data-step="1">
      <span class="step"><%= link_to "1", import_places_path() %></span>
      <span class="title">Import Place</span>
    </li>

    <li data-step="2" class="active">
      <span class="step">
        <%= link_to "2", import_users_path() %>
      </span>
      <span class="title">Import User</span>
    </li>
  </ul>

  <hr>

  <div class="col-sm-12 widget-container-col ui-sortable">
    <!-- #section:custom/widget-box.options.transparent -->
    <div class="widget-box transparent ui-sortable-handle">
      <div class="widget-header">
        <h4 class="widget-title strong">Import user</h4>

        <div class="widget-toolbar no-border">
          <a data-action="settings" href="#">
            <i class="ace-icon fa fa-cog"></i>
          </a>

          <a data-action="reload" href="#">
            <i class="ace-icon fa fa-refresh"></i>
          </a>

          <a data-action="collapse" href="#">
            <i class="ace-icon fa fa-chevron-up"></i>
          </a>

          <a data-action="close" href="#">
            <i class="ace-icon fa fa-times"></i>
          </a>
        </div>
      </div>

      <div class="widget-body">
        <div class="widget-main padding-10 no-padding-left no-padding-right">
          <p> This tool allows you to import a bunch of users to your system by using a <%= link_to raw("user form"), download_template_users_path + ".csv", :method => :get, :class => 'bold_link', :format => :csv %> as a template. </p>
        </div>
      </div>
      <div class="widget-main">
        <div class="form-group">
          <div class="col-xs-6">
            <!-- #section:custom/file-input -->
            <label class="ace-file-input">
              <form id="file-form" method="POST">
                <input type="file" class="file-input" id="file-select" onchange="return handleUploadUserForm();" name="files[]" >
              </form>
            </label>
          </div>
        </div>

        <!-- /section:custom/file-input.filter -->
      </div>
      <div class='tmp-wrapper' id="myTmpTree" style="display:none;">
        <br />
        <div class="table-header">
          Preview for "Latest Uploaded User"
        </div>
        <div id="dynamic-table_wrapper" class="dataTables_wrapper form-inline no-footer">
          <table class="table table-striped table-bordered table-hover" id="errors-table">
            <thead>
              <tr>
                <th>Login</th>
                <th>Full Name</th>
                <th class="hidden-480">Email</th>

                <th>
                  <i class="ace-icon fa fa-clock-o bigger-110 hidden-480"></i>
                  Phone Number
                </th>
                <th class="hidden-480">Place</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody id="tbody">
            </tbody>
          </table>
        </div>
        <button class="btn btn-success" id="btn-import" onclick="handleConfirmImportUser()"> Confirm Import</button>
      </div>
        <!-- /section:custom/widget-box.options.transparent -->
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'shared/health_structure', users: @users %>

app/views/users/new.html.erb
<% content_for(:title) { "User Creation"} %>
<%= breadcrumb [ {"Health Structure" => users_path(place_id: @user.place_id)}, {"User Creation" => nil}] %>

<%= page_header "User Creation" %>

<%= render 'form' %>

app/views/users/profile.html.erb
<%= breadcrumb [ {"Profile" => nil}] %>
<%= simple_form_for :user, { url: change_profile_users_path, method: :put, html: { class: 'form-inline form'} } do |f| %>

  <%=f.input :old_password, required: true, label: 'Old Password', 
             input_html: {class: 'form-control', value: @old_password, autocomplete: :off } %>

  <%=f.input :password, required: true,
             input_html: {class: 'form-control', value: @password, autocomplete: :off } %>

  <%=f.input :password_confirmation, required: true, label: 'Confirm',
             input_html: {class: 'form-control', value: @password_confirmation, autocomplete: :off } %>


  <div class='form-group form-action-group'>
    <label class='control-label'></label>
    <%=f.submit 'Change Password', class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/users/reset.html.erb
<%= breadcrumb [ {"Health Structure" => users_path(place_id: @user.place_id)}, {"Reset Password" => nil}] %>
<%= page_header "Reset password user" %>

<p style='color:gray;font-size: 14px;'>
   <b> <%= @user.username %> </b>'s password has been reset to : 
   <b> <input id='pwd-hidden' type='password' value='<%= @random_password %>' class='pwd-label'/> </b>
   <a class='btn btn-primary btn-app btn-hidden-content' data-ref-id='pwd-hidden' > Show </a>
</p>