config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web => '/sidekiq'

  root 'reports#index'

  get 'sign_in' => 'sessions#new'
  delete 'sign_out' => 'sessions#destroy'

  resources :sessions, only: [:index, :create, :destroy]
  resources :verboice_callbacks, only: [:index]
  resources :dashboards, only: [:index]
  resources :calendars, only: [:index]
  resources :weeks, only: [:index]

  resources :places do
    collection do
      get 'ods_list'
      get 'download_template'
      post 'confirm_upload_location'
      post 'upload_location'
      get 'import'
      get 'export_as_csv'
    end
  end

  resources :users do
    collection do
      get 'profile'
      put 'change_profile'
      get 'download_template'
      post 'confirmed_upload_users'
      post 'upload_users'
      get 'by_place'
      get 'search'
      get 'import'
    end

    member do
      put 'reset'
    end
  end

  resources :settings, only: [:index]
  put 'update_settings' => 'settings#update_settings'

  put 'verboice' => 'settings#verboice'
  get 'project_variables' => 'settings#project_variables'
  get 'external' => 'settings#external'

  get '/steps/manifest' => 'steps#manifest', defaults: { format: :xml }
  post '/steps/validate_hc_worker' => 'steps#validate_hc_worker'

  resources :reports, only: [:index, :destroy] do
    member do
      put :toggle_status
      put :update_week
    end

    collection do
      get :export_as_csv
      get :query_piechart
    end
  end

  resources :report_variables, only: [] do
    member do
      get :play_audio
    end
  end

  resources :variables

  resources :channels do
    member do
      put 'state'
    end
  end
  resources :alerts do
    collection do
      get 'log'
    end
  end
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_health_structure.html.erb
<%= breadcrumb [ {"Health Structure" => nil}] %>
<div class="clearfix">
    <div class="pull-right" style='margin-top: 10px;'>
    <%=link_to export_as_csv_places_path, class: 'btn btn-primary' do %>
     <i class="glyphicon glyphicon-upload"> </i> Export as CSV
    <% end %>
  </div>
</div>
<div class='row'>
  <div class='col-lg-4'>
    <%= render 'shared/search_user' %>
    <%= render 'shared/tree' %>
  </div>

  <div class="col-lg-8">
    <div>
      <span> Selected <i class='glyphicon glyphicon-play' style='font-size: 80%; color: gray; '> </i> </span>
      <span id='selected-tree' style='color: gray;'></span> </div>
    <div id='user-list'> <%= render 'users/list', users: users %> </div>
  </div>
</div>

app/views/shared/_search_user.html.erb
<div class='' style='margin-bottom: 10px;'>
  <%= form_tag search_users_path, method: :get do %>
    <div class="input-group">
      <%= text_field_tag :phone, params[:phone], class: 'form-control', placeholder: 'Reporter phone number' %>
      <span class="input-group-btn">
        <button class="btn btn-primary" type="submit" id='btn-search-user'>
          <i class='glyphicon glyphicon-search'> </i> Search
        </button>
      </span>
    </div>
  <% end %>
</div>

app/views/shared/_tree.html.erb
<div class='tree-wrapper' >
  <ul id="myTree" data-toggle="nav-tree" >
    <%= tree_for(Place.arrange, @place_id) %>
   </ul>
</div>

<div class='tree-action clearfix' style='color: gray;' >
  <div class="pull-left" >
    <%= link_to "Import Health Structure", import_places_path(), :method => :get, :class => 'btn btn-primary to-right' %>
  </div>
  <div class='pull-right'>
    <%= link_to '#', class: 'new-tree' do %>
      <i class='glyphicon glyphicon-plus'> </i>
    <% end %>
    <%= link_edit '', '#', class: 'edit-tree' %>
    <%= link_destroy '', '#', class: 'destroy-tree', method: :delete %>
  </div>
</div>