config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web => '/sidekiq'

  root 'reports#index'

  get 'sign_in' => 'sessions#new'
  delete 'sign_out' => 'sessions#destroy'

  resources :sessions, only: [:index, :create, :destroy]
  resources :verboice_callbacks, only: [:index]
  resources :dashboards, only: [:index]
  resources :calendars, only: [:index]
  resources :weeks, only: [:index]

  resources :places do
    collection do
      get 'ods_list'
      get 'download_template'
      post 'confirm_upload_location'
      post 'upload_location'
      get 'import'
      get 'export_as_csv'
    end
  end

  resources :users do
    collection do
      get 'profile'
      put 'change_profile'
      get 'download_template'
      post 'confirmed_upload_users'
      post 'upload_users'
      get 'by_place'
      get 'search'
      get 'import'
    end

    member do
      put 'reset'
    end
  end

  resources :settings, only: [:index]
  put 'update_settings' => 'settings#update_settings'

  put 'verboice' => 'settings#verboice'
  get 'project_variables' => 'settings#project_variables'
  get 'external' => 'settings#external'

  get '/steps/manifest' => 'steps#manifest', defaults: { format: :xml }
  post '/steps/validate_hc_worker' => 'steps#validate_hc_worker'

  resources :reports, only: [:index, :destroy] do
    member do
      put :toggle_status
      put :update_week
    end

    collection do
      get :export_as_csv
      get :query_piechart
    end
  end

  resources :report_variables, only: [] do
    member do
      get :play_audio
    end
  end

  resources :variables

  resources :channels do
    member do
      put 'state'
    end
  end
  resources :alerts do
    collection do
      get 'log'
    end
  end
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/setting.rb
# == Schema Information
#
# Table name: settings
#
#  id         :integer          not null, primary key
#  var        :string(255)      not null
#  value      :text(65535)
#  thing_id   :integer
#  thing_type :string(30)
#  created_at :datetime
#  updated_at :datetime
#
# Indexes
#
#  index_settings_on_thing_type_and_thing_id_and_var  (thing_type,thing_id,var) UNIQUE
#

class Setting < RailsSettings::CachedSettings
end

app/models/settings.rb
# == Schema Information
#
# Table name: settings
#
#  id         :integer          not null, primary key
#  var        :string(255)      not null
#  value      :text(65535)
#  thing_id   :integer
#  thing_type :string(30)
#  created_at :datetime
#  updated_at :datetime
#
# Indexes
#
#  index_settings_on_thing_type_and_thing_id_and_var  (thing_type,thing_id,var) UNIQUE
#

class Settings < RailsSettings::CachedSettings
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  authorize_resource
  def index
    # to get all items for render list
    Setting[:project] = params[:project] if params[:project]
    @settings   = Setting.unscoped
    @parameters = verboice_parameters
    @variables  = Variable.where(verboice_project_id: Setting[:project])
  end

  def update_settings
    [:project, :project_variable].each do |key|
      Setting[key] = params[key]
    end

    store_variables
    redirect_to settings_path, notice: 'Setting has been saved'
  end

  def store_variables
    Variable.save_from_params(params)
  end

  def verboice
    response = Service::Verboice.auth(params[:email], params[:password])
    Setting[:verboice_email] = params[:email]
    Setting[:verboice_token] = nil

    if response && response["success"]
      Setting[:verboice_token] = response["auth_token"]
      redirect_to settings_path, notice: 'Successfully connected to verboice'
    else
      flash.now[:alert] = 'Could not connect to verboice'
      render :index
    end
  end

  def get_project_variables(project_id)
    project_id.present? ? Service::Verboice.connect(Setting).project_variables(project_id) : []
  end

  def verboice_parameters
    result = {projects: [], project_variables: [] }

    begin
      result[:projects]   = Service::Verboice.connect(Setting).projects
      result[:project_variables]  = get_project_variables(Setting[:project])
    rescue JSON::ParserError
      flash.now.alert = " Failed to fetch some data from verboice"
    end

    result
  end
end

app/helpers/setting_helper.rb
module SettingHelper
  def tab_active_for(tab)
    active_tab = params[:tab].blank? ? :default : params[:tab].to_sym
    active = ( tab == active_tab ) ? 'active' : ''
    active
  end
end

app/views/settings/_connection.html.erb
<%= form_tag verboice_path, class: 'form form-inline', method: :put do %>
  <input type='password' style='display:none;' />
  <div class='input-row'>
    <%= label_tag :email %>
    <%= text_field_tag :email, Setting[:verboice_email], class: 'form-control', autocomplete: :off %>
  </div>

  <div class='input-row'>
    <%= label_tag :password %>
    <%= password_field_tag :password, '', class: 'form-control', autocomplete: :off %>
  </div>

  <div class='input-row'>
    <label></label>
    <%=button_tag 'Connect', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/settings/_form.html.erb
<% variables.each do |variable| %>
  <%= render 'variable', variable: variable, project_variables: project_variables %>
<% end %>

<%= render 'variable', variable: Variable.new, project_variables: project_variables %>

app/views/settings/_setting.html.erb
<div>
    <div>
      <a href='#' class='collasable-link' style="padding: 20px 0px; display:block;">
        <i class='glyphicon glyphicon-cog'> </i> Verboice Connection
      </a>
      <% style = Setting['verboice_token'].blank? ? '' : "style=display:none;" %>

      <div class='collasable-container' <%= style %> >
        <p>
          <% if Setting[:verboice_token].blank? %>
            <span class='vb-status vb-red'> </span> <span class='color-red'> Not Connected </span>
          <% else %>
            <span class='vb vb-green'> </span> <span class='color-green'> Connected </span>
          <% end %>
        </p>

        <%= render 'connection' %>
        <hr />
      </div>

      <% if Setting[:verboice_token].present? %>
        <div style='margin-top: 30px;'>
          <p> <%= render 'verboice' %> </p>
        </div>
      <% end %>

    </div>
</div>

app/views/settings/_variable.html.erb
<div class="panel panel-default panel-variable" style="width: 600px;">

  <div class="panel-head clearfix" style="padding: 10px; background: #d0d0d0;">

    <% if variable.new_record? %>
       <div class="pull-left"> Add new variable mapping </div>
       <div class="pull-right">
         <%= link_to '#', class:'variable-collapsable' do %>
           <i class='icon glyphicon glyphicon-plus'> </i>
         <% end %>
       </div>

    <% else %>
       <div class="pull-left">
          <%= variable.name %>
          <i class='glyphicon glyphicon-link'> </i>
          <%= variable.verboice_name %>
       </div>
       <div class="pull-right">
         <%= link_to '#', class: 'variable-collapsable' do %>
           <i class='icon glyphicon glyphicon-pencil'> </i>
         <% end %>

         <%= link_to variable_path(variable), method: :delete, data: {confirm: 'Are you sure you want to delete this variable'} do %>
           <i class='icon glyphicon glyphicon-trash'> </i>
         <% end %>
       </div>
    <% end %>
  </div>


  <div class="panel-body variable-form" style='border-top: 1px solid #eee; border-bottom: 1px solid #eee; display:none;'>
    <%= simple_form_for variable do |f| %>
      <div class='alert alert-danger error-message' style="display:none;"> ffff</div>
      <div class="clearfix">
          <div class="pull-left" style='width: 45%; padding: 10px;'>
            <%= f.input :name, label: 'Variable name', class: 'form-control s-width' %>
          </div>

          <div class="pull-left" style='width: 10%; padding: 20px; padding-left: 30px; margin-top: 20px;' >
            <i class='glyphicon glyphicon-link'> </i>
          </div>


          <div style='width: 45%; padding: 10px;' class="pull-left">
            <%= f.hidden_field :verboice_name, class: 'verboice-variable-name' %>
            <%= f.label :verboice_id, 'Verboice variable' %>
            <%= f.select :verboice_id,
                       project_variables.map{|p| [ p['name'], p['id'] ] },
                       {include_blank: 'Select variable'},
                       {class: 'form-control s-width verboice-variable-id' } %>
          </div>
      </div>

      <div class="clearfix">
        <div class="pull-left" style='width: 45%; padding: 10px;'>
          <%= f.input :background_color, label: 'Header background color', as: :minicolors, input_html: {data: {
        minicolors: {theme: :bootstrap,defaultValue: '#f3f3f3', position: :right}}} %>
        </div>
        <div class="pull-right" style='width: 45%; padding: 10px;'>
          <%= f.input :text_color, label: 'Text column color', as: :minicolors, input_html: {data: {
        minicolors: {theme: :bootstrap,defaultValue: '#000000', position: :right}}} %>
        </div>
      </div>

      <div class="form-action" style="text-align: right; margin-top: 15px;">
        <button type='reset' class="btn btn-default hide-variable-form" > Cancel </button>
        <button type="button" class="btn btn-primary save-varialble"> Save </button>
      </div>

    <% end %>
  </div>

</div>

app/views/settings/_verboice.html.erb
<h3 class="header-title"> Data mapping to Verboice</h3>
<p class='italic gray callout' >
  Here you can map variable to pull data input from verboice
</p>


<%= form_tag(update_settings_path(tab: params[:tab]), method: :put, class: 'form form-inline', id: 'form-verboice') do %>
  <div class='input-row'>
    <%= label_tag :project, 'Verboice Project' %>
    <%= select_tag :project,
                   options_for_select(@parameters[:projects].map{|p| [ p['name'], p['id'] ] }, Setting[:project]),
                   include_blank: 'Select verboice project',
                   class: 'form-control s-width' %>
  </div>


  <div class='input-row hidden'>
    <%= label_tag :project_variable %>

    <%= select_tag :project_variable,
                   options_for_select(@parameters[:project_variables].map{|p| [ p['name'], p['id'] ] }, Setting[:project_variable]),
                   include_blank: 'Select variable',
                   class: 'form-control s-width' %>
  </div>
<% end %>

<div id='setting-variables'>
 <%= render 'form', project_variables: @parameters[:project_variables], variables: @variables %>
</div>

app/views/settings/index.html.erb
<%= breadcrumb [ {"Settings" => nil} ] %>
<div>
    <div>
      <a href='#' class='collasable-link' style="padding: 20px 0px; display:block;">
        <i class='glyphicon glyphicon-cog'> </i> Verboice Connection
      </a>
      <% style = Setting['verboice_token'].blank? ? '' : "style=display:none;" %>

      <div class='collasable-container' <%= style %> >
        <p>
          <% if Setting[:verboice_token].blank? %>
            <span class='vb-status vb-red'> </span> <span class='color-red'> Not Connected </span>
          <% else %>
            <span class='vb vb-green'> </span> <span class='color-green'> Connected </span>
          <% end %>
        </p>

        <%= render 'connection' %>
        <hr />
      </div>

      <% if Setting[:verboice_token].present? %>
        <div style='margin-top: 30px;'>
          <p> <%= render 'verboice' %> </p>
        </div>
      <% end %>

    </div>
</div>