config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web => '/sidekiq'

  root 'reports#index'

  get 'sign_in' => 'sessions#new'
  delete 'sign_out' => 'sessions#destroy'

  resources :sessions, only: [:index, :create, :destroy]
  resources :verboice_callbacks, only: [:index]
  resources :dashboards, only: [:index]
  resources :calendars, only: [:index]
  resources :weeks, only: [:index]

  resources :places do
    collection do
      get 'ods_list'
      get 'download_template'
      post 'confirm_upload_location'
      post 'upload_location'
      get 'import'
      get 'export_as_csv'
    end
  end

  resources :users do
    collection do
      get 'profile'
      put 'change_profile'
      get 'download_template'
      post 'confirmed_upload_users'
      post 'upload_users'
      get 'by_place'
      get 'search'
      get 'import'
    end

    member do
      put 'reset'
    end
  end

  resources :settings, only: [:index]
  put 'update_settings' => 'settings#update_settings'

  put 'verboice' => 'settings#verboice'
  get 'project_variables' => 'settings#project_variables'
  get 'external' => 'settings#external'

  get '/steps/manifest' => 'steps#manifest', defaults: { format: :xml }
  post '/steps/validate_hc_worker' => 'steps#validate_hc_worker'

  resources :reports, only: [:index, :destroy] do
    member do
      put :toggle_status
      put :update_week
    end

    collection do
      get :export_as_csv
      get :query_piechart
    end
  end

  resources :report_variables, only: [] do
    member do
      get :play_audio
    end
  end

  resources :variables

  resources :channels do
    member do
      put 'state'
    end
  end
  resources :alerts do
    collection do
      get 'log'
    end
  end
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                   :integer          not null, primary key
#  username             :string(255)
#  name                 :string(255)
#  password_digest      :string(255)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  email                :string(255)
#  phone                :string(255)
#  role                 :string(255)
#  place_id             :integer
#  phone_without_prefix :string(255)
#  phd_id_id            :integer
#  phd_id               :integer
#  od_id                :integer
#  channels_count       :integer
#
# Indexes
#
#  index_users_on_phd_id_id  (phd_id_id)
#  index_users_on_place_id   (place_id)
#

class User < ActiveRecord::Base
  has_secure_password(validations: false)
  audited

  belongs_to :place
  belongs_to :phd, class_name: 'Place', foreign_key: 'phd_id'
  belongs_to :od, class_name: 'Place', foreign_key: 'od_id'

  has_many :reports, dependent: :nullify
  has_many :channels
  has_many :alerts
  # password must be present within 6..72
  validates :place_id, presence: true, if: ->(u) { !u.is_admin? }

  validates :password, presence: true, on: :create
  validates :password, length: { in: 6..72}, on: :create
  validates :password, confirmation: true

  # email must be in a valid format and has unique value if it is being provided
  validates :email, email: true, if: ->(u) { u.email.present? }
  validates :email, uniqueness: true, if: ->(u) { u.email.present? }

  validates :phone, uniqueness: true, if: ->(u) { u.phone.present? }

  validates :phone, presence: {message: "Health Center user must has a phone number"}, if: ->(u) { u.place && u.place.is_kind_of_hc?}

  validates :name, presence: true

  validates :username, presence: true
  validates :username, uniqueness: true

  ROLE_ADMIN  = 'Admin'
  ROLE_NORMAL = 'Normal'

  before_save :normalize_attrs
  before_save :set_place_tree

  attr_accessor :old_password

  def self.search phone
    @users = where("1=1")
    @users = where(["phone LIKE ?", "%#{phone}%"]) unless phone.blank?
    @users
  end

  def self.by_place place_id
    users = User.order("name DESC").all
    if(place_id.present?)
      users = users.where(place_id: place_id)
    end
    users
  end

  def set_place_tree
    if self.place
      self.phd = self.place.phd
      self.od  = self.place.od
    end
  end

  def normalize_attrs
    self.role = User::ROLE_NORMAL unless self.role.present?
    self.username.downcase!
    self.phone_without_prefix = self.phone.present? ? Tel.new(self.phone).without_prefix : nil
  end

  def self.authenticate(username, password)
    user = User.find_by!(username: username.downcase)
    user.authenticate(password)
  rescue ActiveRecord::RecordNotFound
    false
  end

  def self.visible_roles
    [ROLE_NORMAL, ROLE_ADMIN]
  end

  def is_admin?
    role == User::ROLE_ADMIN
  end

  def is_normal?
    role == User::ROLE_NORMAL
  end

  def change_password old_password, new_password, confirm
    if self.authenticate(old_password)
      self.password = new_password
      self.password_confirmation = confirm
      save
    else
      errors.add(:old_password, 'does not matched')
      false
    end
  end

  def self.hc_worker? phone_number
    phone_without_prefix = Tel.new(phone_number).without_prefix
    user = User.find_by(phone_without_prefix: phone_without_prefix)
    !user.nil? && user.place && user.place.is_kind_of_hc?
  end

  def self.decode_and_validate_user_csv(string)
    csv = CSV.parse(string)
    errors = []
    datas = []
    index = 0
    csv.slice!(0)
    csv.each do |row|
      valid = validate_row(index, row, csv)
      unless valid[:status]
        row.push(valid[:errors])
      end
      datas.push row
      index = index + 1
    end
    return {:data => datas}
  end

  def self.validate_row(index, row, csv)
    if row[4].strip.present? and row[5].strip.present? and row[4] != row[5]
      errors.push({:type => 'not_match', :field => 'password'})
    elsif row[4].strip.empty? or row[5].strip.empty?
      errors.push({:type => 'missing', :field => 'password'})
    end
    if row[6].strip.present?
      place = Place.find_by_code(row[6])
      unless place
        errors.push({:type => 'unknown', :field => 'place'})
      else
        row[6] = "#{place.name}(#{place.code}) - #{place.kind_of}"
      end
    elsif row[4].strip.empty? or row[5].strip.empty?
      errors.push({:type => 'missing', :field => 'place'})
    end
    errors = calculateError(csv, row, index)

    list_errors = generateErrorText(errors)

    if list_errors.size > 0
      return {:status => false, errors: list_errors}
    else
      return {:status => true}
    end
  end

  def self.calculateError(csv, row, index)
    errors = []
    i = 0
    errors.push({:type => 'duplicate', :field => 'login', :index => nil}) if User.find_by_username(row[0])
    # errors.push({:type => 'duplicate', :field => 'email', :index => nil}) if User.find_by_email(row[2])
    errors.push({:type => 'duplicate', :field => 'phone', :index => nil}) if User.find_by_phone(row[3])
    csv.each do |value|
      if i < index.to_i
        if row[0] == value[0]
          errors.push({:type => 'duplicate', :field => 'login', :index => (i+1)})
        elsif row[0].strip.empty?
          errors.push({:type => 'missing', :field => 'login'})
        end
        # if row[2] == value[2]
        #   errors.push({:type => 'duplicate', :field => 'email', :index => (i+1)})
        # elsif row[2].strip.empty?
        #   errors.push({:type => 'missing', :field => 'email'})
        # end
        if row[3] == value[3]
          errors.push({:type => 'duplicate', :field => 'phone', :index => (i+1)})
        elsif row[3].strip.empty?
          errors.push({:type => 'missing', :field => 'phone'})
        end
      end
      i = i + 1
    end
    return errors;
  end

  def self.generateErrorText(errors)
    list_errors = []
    errors.each do |error|
      case error[:field]
      when 'login'
        if error[:type] == 'duplicate'
          list_errors.push(generateDuplicateErrrorText(error[:index], "login"))
        elsif error[:type] == 'missing'
          list_errors.push(generateMissingErrrorText("login"))
        end
      when 'email'
        if error[:type] == 'duplicate'
          list_errors.push(generateDuplicateErrrorText(error[:index], "email"))
        elsif error[:type] == 'dupmissinglicate'
          list_errors.push(generateMissingErrrorText("email"))
        end
      when 'phone'
        if error[:type] == 'duplicate'
          list_errors.push(generateDuplicateErrrorText(error[:index], "phone number"))
        elsif error[:type] == 'missing'
          list_errors.push(generateMissingErrrorText("phone number"))
        end
      when 'password'
        if error[:type] == 'not_match'
          list_errors.push("Password not match on row #{index}")
        elsif error[:type] == 'missing'
          list_errors.push("Password or confirmation password is missing")
        end
      when 'place'
        if error[:type] == 'missing'
          list_errors.push("Place is missing")
        elsif error[:type] == 'unknown'
          list_errors.push("Place is unknown")
        end
      end
    end
    return list_errors
  end

  def self.generateDuplicateErrrorText(index, field)
    if index
      return "Duplicated #{field} value on row #{index}."
    else
      return "Duplicated #{field} with existing user #{field}."
    end
  end

  def self.generateMissingErrrorText(field)
    return "Missing #{field} value."
  end

  def self.decode_and_save_user_csv(string)
    csv = CSV.parse(string)
    datas = []
    csv.slice!(0)
    csv.each do |row|
      datas.push row
      place = Place.find_by_code(row[6].strip)
      phd_id = place.phd.id
      od_id = nil
      od_id = place.od.id if place.od
      User.create!(
          username: row[0],
          name: row[1],
          email: row[2],
          phone: row[3],
          role: "Normal",
          place_id: place.id,
          password: row[4],
          password_confirmation: row[5],
          phd_id: phd_id,
          od_id: od_id
      )
    end
    return {:data => datas}
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  authorize_resource

  helper_method :sort_column, :sort_direction

  def required_admin_role!

  end

  def index
    reports = UserContext.new(current_user).reports.includes(:report_variables, :user, :phd, :od)
                     .effective
                     .filter(params)
                     .includes(:phd, :od)
    reports = sort_column ? reports.order(sort_column + " " + sort_direction) : reports.order('id DESC')
    @report_ids = reports.map(&:id)
    @reports_by_page = reports.page(params[:page])
    @variables = Variable.applied(Setting[:project])
  end

  def query_piechart
    @reports = UserContext.new(current_user)
                     .reports
                     .includes(:report_variables, :user, :phd, :od)
                     .effective
                     .filter(params)
                     .includes(:phd, :od)
                     .order('id DESC')
    data_review = Report.to_piechart_reviewed(@reports)
    data_phd = Report.to_piechart_phd(@reports)
    render :json => {:review => data_review, :phd => data_phd}
  end

  def export_as_csv
    file = ReportCsv.new(UserContext.new(current_user)).start(params)
    send_file file, type: "text/csv"
  end

  def toggle_status
    report = Report.find(params[:id])
    authorize! :update, report

    if report.toggle_status
      head :ok
    else
      render nothing: true, status: 400
    end
  end

  def update_week
    report = Report.find(params[:id])
    authorize! :update, report

    week = Calendar::Week.parse(params[:week])

    if report.reviewed_as!(week.year.number, week.week_number)
      head :ok
    else
      render nothing: true, status: :not_found
    end
  end

  def destroy
    @report = Report.find(params[:id])
    authorize! :destroy, @report

    @report.delete_status = true
    if @report.save
      redirect_to reports_path, notice: 'Report has been deleted successfully'
    else
      redirect_to reports_path, alert: 'Failed to delete report'
    end
  end

  private

  def sort_column
    Report.column_names.include?(params[:sort]) ? params[:sort] : nil
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {from: params[:from], to: params[:to], phd: params[:phd], od: params[:od], reviewed: params[:reviewed], sort: column, direction: direction}, {:class => css_class}
  end
end

app/views/reports/_filter.html.erb
<script>
  fromWeek = '<%= params[:from_week] %>';
  toWeek = '<%= params[:to_week] %>';
  currentYear = '<%= params[:year].present? ? params[:year] : Time.now.year %>';
</script>

<% year = params[:year].present? ? params[:year].to_i : Time.now.year %>

<div class='panel panel-default'>
  <div class='panel-heading'>
    <h3 class='panel-title'>Filter</h3>
  </div>

  <div class="panel-body" style='padding: 10px 0px;'>
    <%= form_tag reports_path, method: 'GET' do |f| %>
      <div class='input-row col-lg-2'>
        <%= label_tag :reviewed, 'Reviewed Status' %>
        <%= select_tag :reviewed, options_for_select([[ "Reviewed", 1], ["New", 0]], params[:reviewed]),
                       class: 'form-control', include_blank: "All" %>
      </div>

      <div class='input-row col-lg-2 year' style="display: none;">
        <%= label_tag :year, 'Period' %>
        <%= select_tag :year, options_for_select(Calendar::Year.new(Time.now.year).near_by(2), year),
                       class: 'form-control' %>
      </div>

      <div class='input-row col-lg-2 from-week-group' style='display: none;'>
        <label>From</label>
        <%= select_tag :from_week, options_for_select(Calendar::Year.new(year).available_weeks.map { |w| [w.display(Calendar::Week::DISPLAY_ADVANCED_MODE), w.week_number]}, params[:from_week]), class: 'form-control', include_blank: 'All' %>
      </div>
      <div class='input-row col-lg-2 to-week-group' style='display: none;'>
        <label>To</label>
        <%= select_tag :to_week, options_for_select(Calendar::Year.new(year).available_weeks.map { |w| [w.display(Calendar::Week::DISPLAY_ADVANCED_MODE), w.week_number]}, params[:to_week]), class: 'form-control', include_blank: 'All' %>
      </div>

      <div class='input-row col-lg-2'>
        <%= label_tag :phd, 'PHD' %>
        <%= select_tag :phd, options_for_select(UserContext.new(current_user).phds_list, params[:phd]),
                       class: 'form-control', include_blank: 'All' %>
      </div>

      <div class='input-row col-lg-2'>
        <%= label_tag :od, 'OD' %>
        <%= select_tag :od, options_for_select(UserContext.new(current_user).ods_list(params[:phd]), params[:od]),
                       class: 'form-control', prompt: "All" %>
      </div>

      <div class='input-row col-lg-2'>
        <button class='btn btn-primary' style='margin-top: 25px;'>
          <i class='glyphicon glyphicon-search'> </i> Filter
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/reports/index.html.erb
<%= breadcrumb [ {"Reports" => nil}] %>
<%= page_title "Call list" %>
<%= render 'filter' %>

<div class="clearfix">
  <div class="pull-left">
    <h2 class="header-title">List of report</h2>
  </div>
  <div class="pull-right" style='margin-top: 10px;'>
    <%=link_to export_as_csv_reports_path(request.query_parameters), class: 'btn btn-primary' do %>
     <i class="glyphicon glyphicon-upload"> </i> Export as CSV
    <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="report table table-striped table-bordered table-hover">
    <thead>
    <tr style="color: black">
        <td>Reported date</td>
        <td>PHD</td>
        <td>OD</td>
        <td>Phone</td>
        <td><%= sortable "user_id", "Username" %></td>
        <td>Duration<br/>(second)</td>
        <% @variables.each do |variable| %>
        <td style="width:150px; background-color: <%= variable.background_color%>;" > <%= variable.name %> </td>
        <% end %>
        <td>Reviewed and assigned</td>
        <td>Action</td>
      </tr>
    </thead>

    <tbody>
    <% if @reports_by_page.size > 0 %>
      <tr style="font-weight: bold;">
        <td>Total</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <% @variables.each do |variable| %>
        <td style='color: <%= variable.text_color%>;'><%= variable.total_report_value(@report_ids) %></td>
        <% end -%>
        <td></td>
        <td></td>
      </tr>
      <% @reports_by_page.each_with_index do |report, index| %>
          <tr>
            <td> <%= report.called_at %></td>

            <td>
                <%= link_to(report.phd.name, users_path(place_id: report.phd.try(:id))) if current_user.is_admin? && report.phd %>
                <%= report.phd.try(:name) if current_user.is_normal? %>
            </td>

            <td>
               <%= link_to(report.od.name, users_path(place_id: report.od.try(:id))) if current_user.is_admin? && report.od %>
               <%= report.od.try(:name) if current_user.is_normal? %>
            </td>

            <td><%= report.phone %></td>
            <td> <%= report.user.try(:name)%> </td>
            <td> <%= report.duration%> </td>

            <% @variables.each do |variable| %>
            <td style='color: <%= variable.text_color%>;'>
                <% report_variable = report.report_variables.select{|report_variable| report_variable.variable_id == variable.id}.first %>

                <div style="position: relative">
                  <% if report_variable && report_variable.is_reached_threshold %>
                    <%= image_tag 'warning.gif', style: 'top:0; right: 0; position: absolute' %>
                  <% end %>
                  <%= display_report_variable(report_variable) %>
                </div>
              </td>
            <% end %>

            <td>
              <%= select_tag(report.id, options_for_select(Calendar::Year.new(Time.now.year).available_weeks.map { |w| w.display }, "w#{report.week}-#{report.year}"), { include_blank: true, class: 'weekly-report' }) %>
            </td>

            <td>
              <%= link_to report_path(report), method: :delete, data: {confirm: 'Are you sure to delete ?'} do %>
                  <i class='glyphicon glyphicon-trash red'> </i>
              <% end %>

            </td>
          </tr>
        <% end %>
      <% else %>
        <td colspan="<%= (8 + @variables.size) %>">
          <div class="alert alert-danger center" style="margin-bottom: 0px">
            There is no record.
            <br>
          </div>
        </td>
      <% end %>
    </tbody>
  </table>
</div>

<div class="clearfix">
  <%= paginate_for(@reports_by_page) %>
</div>